import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/otterscale-service",
    },
    {
      type: "category",
      label: "ApplicationService",
      link: {
        type: "doc",
        id: "api/application-service",
      },
      items: [
        {
          type: "doc",
          id: "api/application-service-list-namespaces",
          label: "ListNamespaces",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/application-service-list-applications",
          label: "ListApplications",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/application-service-get-application",
          label: "GetApplication",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/application-service-restart-application",
          label: "RestartApplication",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/application-service-scale-application",
          label: "ScaleApplication",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/application-service-delete-application-pod",
          label: "DeleteApplicationPod",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/application-service-write-tty",
          label: "WriteTTY",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/application-service-list-releases",
          label: "ListReleases",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/application-service-create-release",
          label: "CreateRelease",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/application-service-update-release",
          label: "UpdateRelease",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/application-service-delete-release",
          label: "DeleteRelease",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/application-service-rollback-release",
          label: "RollbackRelease",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/application-service-list-charts",
          label: "ListCharts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/application-service-get-chart",
          label: "GetChart",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/application-service-get-chart-metadata",
          label: "GetChartMetadata",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/application-service-list-storage-classes",
          label: "ListStorageClasses",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "InstanceService",
      link: {
        type: "doc",
        id: "api/instance-service",
      },
      items: [
        {
          type: "doc",
          id: "api/instance-service-list-virtual-machines",
          label: "ListVirtualMachines",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-get-virtual-machine",
          label: "GetVirtualMachine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-create-virtual-machine",
          label: "CreateVirtualMachine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-delete-virtual-machine",
          label: "DeleteVirtualMachine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-attach-virtual-machine-disk",
          label: "AttachVirtualMachineDisk",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-detach-virtual-machine-disk",
          label: "DetachVirtualMachineDisk",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-create-virtual-machine-clone",
          label: "CreateVirtualMachineClone",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-delete-virtual-machine-clone",
          label: "DeleteVirtualMachineClone",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-create-virtual-machine-snapshot",
          label: "CreateVirtualMachineSnapshot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-delete-virtual-machine-snapshot",
          label: "DeleteVirtualMachineSnapshot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-create-virtual-machine-restore",
          label: "CreateVirtualMachineRestore",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-delete-virtual-machine-restore",
          label: "DeleteVirtualMachineRestore",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-start-virtual-machine",
          label: "StartVirtualMachine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-stop-virtual-machine",
          label: "StopVirtualMachine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-restart-virtual-machine",
          label: "RestartVirtualMachine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-pause-instance",
          label: "PauseInstance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-resume-instance",
          label: "ResumeInstance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-migrate-instance",
          label: "MigrateInstance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-vnc-instance",
          label: "VNCInstance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-list-data-volumes",
          label: "ListDataVolumes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-get-data-volume",
          label: "GetDataVolume",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-create-data-volume",
          label: "CreateDataVolume",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-delete-data-volume",
          label: "DeleteDataVolume",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-extend-data-volume",
          label: "ExtendDataVolume",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-list-instance-types",
          label: "ListInstanceTypes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-get-instance-type",
          label: "GetInstanceType",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-create-instance-type",
          label: "CreateInstanceType",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-delete-instance-type",
          label: "DeleteInstanceType",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-create-virtual-machine-service",
          label: "CreateVirtualMachineService",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-update-virtual-machine-service",
          label: "UpdateVirtualMachineService",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/instance-service-delete-virtual-machine-service",
          label: "DeleteVirtualMachineService",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "StorageService",
      link: {
        type: "doc",
        id: "api/storage-service",
      },
      items: [
        {
          type: "doc",
          id: "api/storage-service-list-mo-ns",
          label: "ListMONs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-list-os-ds",
          label: "ListOSDs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-do-smart",
          label: "DoSMART",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-list-pools",
          label: "ListPools",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-create-pool",
          label: "CreatePool",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-update-pool",
          label: "UpdatePool",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-delete-pool",
          label: "DeletePool",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-list-images",
          label: "ListImages",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-create-image",
          label: "CreateImage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-update-image",
          label: "UpdateImage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-delete-image",
          label: "DeleteImage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-create-image-snapshot",
          label: "CreateImageSnapshot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-delete-image-snapshot",
          label: "DeleteImageSnapshot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-rollback-image-snapshot",
          label: "RollbackImageSnapshot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-protect-image-snapshot",
          label: "ProtectImageSnapshot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-unprotect-image-snapshot",
          label: "UnprotectImageSnapshot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-list-volumes",
          label: "ListVolumes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-list-subvolumes",
          label: "ListSubvolumes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-create-subvolume",
          label: "CreateSubvolume",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-update-subvolume",
          label: "UpdateSubvolume",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-delete-subvolume",
          label: "DeleteSubvolume",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-grant-subvolume-export-access",
          label: "GrantSubvolumeExportAccess",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-revoke-subvolume-export-access",
          label: "RevokeSubvolumeExportAccess",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-create-subvolume-snapshot",
          label: "CreateSubvolumeSnapshot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-delete-subvolume-snapshot",
          label: "DeleteSubvolumeSnapshot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-list-subvolume-groups",
          label: "ListSubvolumeGroups",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-create-subvolume-group",
          label: "CreateSubvolumeGroup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-update-subvolume-group",
          label: "UpdateSubvolumeGroup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-delete-subvolume-group",
          label: "DeleteSubvolumeGroup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-list-buckets",
          label: "ListBuckets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-create-bucket",
          label: "CreateBucket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-update-bucket",
          label: "UpdateBucket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-delete-bucket",
          label: "DeleteBucket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-list-users",
          label: "ListUsers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-create-user",
          label: "CreateUser",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-update-user",
          label: "UpdateUser",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-delete-user",
          label: "DeleteUser",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-create-user-key",
          label: "CreateUserKey",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/storage-service-delete-user-key",
          label: "DeleteUserKey",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "FacilityService",
      link: {
        type: "doc",
        id: "api/facility-service",
      },
      items: [
        {
          type: "doc",
          id: "api/facility-service-list-facilities",
          label: "ListFacilities",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/facility-service-get-facility",
          label: "GetFacility",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/facility-service-create-facility",
          label: "CreateFacility",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/facility-service-update-facility",
          label: "UpdateFacility",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/facility-service-delete-facility",
          label: "DeleteFacility",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/facility-service-expose-facility",
          label: "ExposeFacility",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/facility-service-add-facility-units",
          label: "AddFacilityUnits",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/facility-service-resolve-facility-unit-errors",
          label: "ResolveFacilityUnitErrors",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/facility-service-list-actions",
          label: "ListActions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/facility-service-do-action",
          label: "DoAction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/facility-service-list-charms",
          label: "ListCharms",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/facility-service-get-charm",
          label: "GetCharm",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/facility-service-get-charm-metadata",
          label: "GetCharmMetadata",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/facility-service-list-charm-artifacts",
          label: "ListCharmArtifacts",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "OrchestratorService",
      link: {
        type: "doc",
        id: "api/orchestrator-service",
      },
      items: [
        {
          type: "doc",
          id: "api/orchestrator-service-list-essentials",
          label: "ListEssentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/orchestrator-service-create-node",
          label: "CreateNode",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/orchestrator-service-create-cluster",
          label: "CreateCluster",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/orchestrator-service-add-cluster-units",
          label: "AddClusterUnits",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/orchestrator-service-list-kubernetes-node-labels",
          label: "ListKubernetesNodeLabels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/orchestrator-service-update-kubernetes-node-labels",
          label: "UpdateKubernetesNodeLabels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/orchestrator-service-list-gpu-relations-by-machine",
          label: "ListGPURelationsByMachine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/orchestrator-service-list-gpu-relations-by-model",
          label: "ListGPURelationsByModel",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/orchestrator-service-list-plugins",
          label: "ListPlugins",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "NetworkService",
      link: {
        type: "doc",
        id: "api/network-service",
      },
      items: [
        {
          type: "doc",
          id: "api/network-service-list-networks",
          label: "ListNetworks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/network-service-create-network",
          label: "CreateNetwork",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/network-service-create-ip-range",
          label: "CreateIPRange",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/network-service-delete-network",
          label: "DeleteNetwork",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/network-service-delete-ip-range",
          label: "DeleteIPRange",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/network-service-update-fabric",
          label: "UpdateFabric",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/network-service-update-vlan",
          label: "UpdateVLAN",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/network-service-update-subnet",
          label: "UpdateSubnet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/network-service-update-ip-range",
          label: "UpdateIPRange",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "MachineService",
      link: {
        type: "doc",
        id: "api/machine-service",
      },
      items: [
        {
          type: "doc",
          id: "api/machine-service-list-machines",
          label: "ListMachines",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/machine-service-get-machine",
          label: "GetMachine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/machine-service-create-machine",
          label: "CreateMachine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/machine-service-delete-machine",
          label: "DeleteMachine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/machine-service-power-off-machine",
          label: "PowerOffMachine",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/machine-service-add-machine-tags",
          label: "AddMachineTags",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/machine-service-remove-machine-tags",
          label: "RemoveMachineTags",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/machine-service-list-tags",
          label: "ListTags",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/machine-service-get-tag",
          label: "GetTag",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/machine-service-create-tag",
          label: "CreateTag",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/machine-service-delete-tag",
          label: "DeleteTag",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "EnvironmentService",
      link: {
        type: "doc",
        id: "api/environment-service",
      },
      items: [
        {
          type: "doc",
          id: "api/environment-service-check-health",
          label: "CheckHealth",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/environment-service-update-config",
          label: "UpdateConfig",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/environment-service-get-prometheus",
          label: "GetPrometheus",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/environment-service-get-premium-tier",
          label: "GetPremiumTier",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "ConfigurationService",
      link: {
        type: "doc",
        id: "api/configuration-service",
      },
      items: [
        {
          type: "doc",
          id: "api/configuration-service-get-configuration",
          label: "GetConfiguration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/configuration-service-update-ntp-server",
          label: "UpdateNTPServer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/configuration-service-update-package-repository",
          label: "UpdatePackageRepository",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/configuration-service-update-helm-repository",
          label: "UpdateHelmRepository",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/configuration-service-create-boot-image",
          label: "CreateBootImage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/configuration-service-set-default-boot-image",
          label: "SetDefaultBootImage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/configuration-service-import-boot-images",
          label: "ImportBootImages",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/configuration-service-is-importing-boot-images",
          label: "IsImportingBootImages",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/configuration-service-list-boot-image-selections",
          label: "ListBootImageSelections",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/configuration-service-list-test-results",
          label: "ListTestResults",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/configuration-service-create-test-result",
          label: "CreateTestResult",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/configuration-service-delete-test-result",
          label: "DeleteTestResult",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/configuration-service-list-internal-object-services",
          label: "ListInternalObjectServices",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "ModelService",
      link: {
        type: "doc",
        id: "api/model-service",
      },
      items: [
        {
          type: "doc",
          id: "api/model-service-list-models",
          label: "ListModels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/model-service-get-model",
          label: "GetModel",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/model-service-create-model",
          label: "CreateModel",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/model-service-delete-model",
          label: "DeleteModel",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "BootstrapService",
      link: {
        type: "doc",
        id: "api/bootstrap-service",
      },
      items: [
        {
          type: "doc",
          id: "api/bootstrap-service-update-status",
          label: "UpdateStatus",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "ScopeService",
      link: {
        type: "doc",
        id: "api/scope-service",
      },
      items: [
        {
          type: "doc",
          id: "api/scope-service-list-scopes",
          label: "ListScopes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/scope-service-create-scope",
          label: "CreateScope",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/schemas/nullvalue",
          label: "NullValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/google-protobuf-empty",
          label: "google.protobuf.Empty",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listvalue",
          label: "ListValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/google-protobuf-struct",
          label: "google.protobuf.Struct",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fieldsentry",
          label: "FieldsEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/google-protobuf-timestamp",
          label: "google.protobuf.Timestamp",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/google-protobuf-value",
          label: "google.protobuf.Value",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/application",
          label: "Application",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/chart",
          label: "Chart",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/customization",
          label: "Customization",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/dependency",
          label: "Dependency",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/maintainer",
          label: "Maintainer",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/metadata",
          label: "Metadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/version",
          label: "Version",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/condition",
          label: "Condition",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/container",
          label: "Container",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/labelsentry",
          label: "LabelsEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/persistentvolumeclaim",
          label: "PersistentVolumeClaim",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pod",
          label: "Pod",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/release",
          label: "Release",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/service",
          label: "Service",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/port",
          label: "Port",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createreleaserequest",
          label: "CreateReleaseRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/valuesmapentry",
          label: "ValuesMapEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deleteapplicationpodrequest",
          label: "DeleteApplicationPodRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletereleaserequest",
          label: "DeleteReleaseRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/executettyrequest",
          label: "ExecuteTTYRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/executettyresponse",
          label: "ExecuteTTYResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getapplicationrequest",
          label: "GetApplicationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getchartmetadatarequest",
          label: "GetChartMetadataRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getchartrequest",
          label: "GetChartRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listapplicationsrequest",
          label: "ListApplicationsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listapplicationsresponse",
          label: "ListApplicationsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listchartsrequest",
          label: "ListChartsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listchartsresponse",
          label: "ListChartsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listnamespacesrequest",
          label: "ListNamespacesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listnamespacesresponse",
          label: "ListNamespacesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listreleasesrequest",
          label: "ListReleasesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listreleasesresponse",
          label: "ListReleasesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/liststorageclassesrequest",
          label: "ListStorageClassesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/liststorageclassesresponse",
          label: "ListStorageClassesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/namespace",
          label: "Namespace",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/labelsentry",
          label: "LabelsEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/restartapplicationrequest",
          label: "RestartApplicationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/rollbackreleaserequest",
          label: "RollbackReleaseRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/scaleapplicationrequest",
          label: "ScaleApplicationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/storageclass",
          label: "StorageClass",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/parametersentry",
          label: "ParametersEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatereleaserequest",
          label: "UpdateReleaseRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/watchlogsrequest",
          label: "WatchLogsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/watchlogsresponse",
          label: "WatchLogsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/writettyrequest",
          label: "WriteTTYRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connect-protocol-version",
          label: "Connect-Protocol-Version",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connect-timeout-ms",
          label: "Connect-Timeout-Ms",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connect-error",
          label: "Connect Error",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/connect-error-details-any",
          label: "connect.error_details.Any",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/type",
          label: "Type",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/bus",
          label: "Bus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/type",
          label: "Type",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/attachvirtualmachinediskrequest",
          label: "AttachVirtualMachineDiskRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createdatavolumerequest",
          label: "CreateDataVolumeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createinstancetyperequest",
          label: "CreateInstanceTypeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createvirtualmachineclonerequest",
          label: "CreateVirtualMachineCloneRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createvirtualmachinerequest",
          label: "CreateVirtualMachineRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createvirtualmachinerestorerequest",
          label: "CreateVirtualMachineRestoreRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createvirtualmachineservicerequest",
          label: "CreateVirtualMachineServiceRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createvirtualmachinesnapshotrequest",
          label: "CreateVirtualMachineSnapshotRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/datavolume",
          label: "DataVolume",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/condition",
          label: "Condition",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/source",
          label: "Source",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletedatavolumerequest",
          label: "DeleteDataVolumeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deleteinstancetyperequest",
          label: "DeleteInstanceTypeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletevirtualmachineclonerequest",
          label: "DeleteVirtualMachineCloneRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletevirtualmachinerequest",
          label: "DeleteVirtualMachineRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletevirtualmachinerestorerequest",
          label: "DeleteVirtualMachineRestoreRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletevirtualmachineservicerequest",
          label: "DeleteVirtualMachineServiceRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletevirtualmachinesnapshotrequest",
          label: "DeleteVirtualMachineSnapshotRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/detachvirtualmachinediskrequest",
          label: "DetachVirtualMachineDiskRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/extenddatavolumerequest",
          label: "ExtendDataVolumeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getdatavolumerequest",
          label: "GetDataVolumeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getinstancetyperequest",
          label: "GetInstanceTypeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getvirtualmachinerequest",
          label: "GetVirtualMachineRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/instancetype",
          label: "InstanceType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listdatavolumesrequest",
          label: "ListDataVolumesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listdatavolumesresponse",
          label: "ListDataVolumesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listinstancetypesrequest",
          label: "ListInstanceTypesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listinstancetypesresponse",
          label: "ListInstanceTypesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listvirtualmachinesrequest",
          label: "ListVirtualMachinesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listvirtualmachinesresponse",
          label: "ListVirtualMachinesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/migrateinstancerequest",
          label: "MigrateInstanceRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pauseinstancerequest",
          label: "PauseInstanceRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/restartvirtualmachinerequest",
          label: "RestartVirtualMachineRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/resumeinstancerequest",
          label: "ResumeInstanceRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/startvirtualmachinerequest",
          label: "StartVirtualMachineRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/stopvirtualmachinerequest",
          label: "StopVirtualMachineRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatevirtualmachineservicerequest",
          label: "UpdateVirtualMachineServiceRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/vncinstancerequest",
          label: "VNCInstanceRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/vncinstanceresponse",
          label: "VNCInstanceResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/virtualmachine",
          label: "VirtualMachine",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/clone",
          label: "Clone",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/disk",
          label: "Disk",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/volume",
          label: "Volume",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/source",
          label: "Source",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/restore",
          label: "Restore",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/snapshot",
          label: "Snapshot",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/acl",
          label: "ACL",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pooltype",
          label: "PoolType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/bucket",
          label: "Bucket",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/grant",
          label: "Grant",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createbucketrequest",
          label: "CreateBucketRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createimagerequest",
          label: "CreateImageRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createimagesnapshotrequest",
          label: "CreateImageSnapshotRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createpoolrequest",
          label: "CreatePoolRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createsubvolumegrouprequest",
          label: "CreateSubvolumeGroupRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createsubvolumerequest",
          label: "CreateSubvolumeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createsubvolumesnapshotrequest",
          label: "CreateSubvolumeSnapshotRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createuserkeyrequest",
          label: "CreateUserKeyRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createuserrequest",
          label: "CreateUserRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletebucketrequest",
          label: "DeleteBucketRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deleteimagerequest",
          label: "DeleteImageRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deleteimagesnapshotrequest",
          label: "DeleteImageSnapshotRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletepoolrequest",
          label: "DeletePoolRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletesubvolumegrouprequest",
          label: "DeleteSubvolumeGroupRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletesubvolumerequest",
          label: "DeleteSubvolumeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletesubvolumesnapshotrequest",
          label: "DeleteSubvolumeSnapshotRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deleteuserkeyrequest",
          label: "DeleteUserKeyRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deleteuserrequest",
          label: "DeleteUserRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/dosmartrequest",
          label: "DoSMARTRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/dosmartresponse",
          label: "DoSMARTResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deviceoutputmapentry",
          label: "DeviceOutputMapEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/output",
          label: "Output",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/grantsubvolumeexportaccessrequest",
          label: "GrantSubvolumeExportAccessRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/image",
          label: "Image",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/snapshot",
          label: "Snapshot",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listbucketsrequest",
          label: "ListBucketsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listbucketsresponse",
          label: "ListBucketsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listimagesrequest",
          label: "ListImagesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listimagesresponse",
          label: "ListImagesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listmonsrequest",
          label: "ListMONsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listmonsresponse",
          label: "ListMONsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listosdsrequest",
          label: "ListOSDsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listosdsresponse",
          label: "ListOSDsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listpoolsrequest",
          label: "ListPoolsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listpoolsresponse",
          label: "ListPoolsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listsubvolumegroupsrequest",
          label: "ListSubvolumeGroupsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listsubvolumegroupsresponse",
          label: "ListSubvolumeGroupsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listsubvolumesrequest",
          label: "ListSubvolumesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listsubvolumesresponse",
          label: "ListSubvolumesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listusersrequest",
          label: "ListUsersRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listusersresponse",
          label: "ListUsersResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listvolumesrequest",
          label: "ListVolumesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listvolumesresponse",
          label: "ListVolumesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/mon",
          label: "MON",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/machine",
          label: "Machine",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/osd",
          label: "OSD",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pool",
          label: "Pool",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/placementgroupstateentry",
          label: "PlacementGroupStateEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/protectimagesnapshotrequest",
          label: "ProtectImageSnapshotRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/revokesubvolumeexportaccessrequest",
          label: "RevokeSubvolumeExportAccessRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/rollbackimagesnapshotrequest",
          label: "RollbackImageSnapshotRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/subvolume",
          label: "Subvolume",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/export",
          label: "Export",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/snapshot",
          label: "Snapshot",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/subvolumegroup",
          label: "SubvolumeGroup",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/unprotectimagesnapshotrequest",
          label: "UnprotectImageSnapshotRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatebucketrequest",
          label: "UpdateBucketRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updateimagerequest",
          label: "UpdateImageRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatepoolrequest",
          label: "UpdatePoolRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatesubvolumegrouprequest",
          label: "UpdateSubvolumeGroupRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatesubvolumerequest",
          label: "UpdateSubvolumeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updateuserrequest",
          label: "UpdateUserRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/user",
          label: "User",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/key",
          label: "Key",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/volume",
          label: "Volume",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/addfacilityunitsrequest",
          label: "AddFacilityUnitsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/addfacilityunitsresponse",
          label: "AddFacilityUnitsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/constraint",
          label: "Constraint",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createfacilityrequest",
          label: "CreateFacilityRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletefacilityrequest",
          label: "DeleteFacilityRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/doactionrequest",
          label: "DoActionRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/exposefacilityrequest",
          label: "ExposeFacilityRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/facility",
          label: "Facility",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/action",
          label: "Action",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/charm",
          label: "Charm",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/artifact",
          label: "Artifact",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/base",
          label: "Base",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/metadata",
          label: "Metadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/status",
          label: "Status",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/unit",
          label: "Unit",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getcharmmetadatarequest",
          label: "GetCharmMetadataRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getcharmrequest",
          label: "GetCharmRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getfacilityrequest",
          label: "GetFacilityRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listactionsrequest",
          label: "ListActionsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listactionsresponse",
          label: "ListActionsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listcharmartifactsrequest",
          label: "ListCharmArtifactsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listcharmartifactsresponse",
          label: "ListCharmArtifactsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listcharmsrequest",
          label: "ListCharmsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listcharmsresponse",
          label: "ListCharmsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listfacilitiesrequest",
          label: "ListFacilitiesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listfacilitiesresponse",
          label: "ListFacilitiesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/placement",
          label: "Placement",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/resolvefacilityuniterrorsrequest",
          label: "ResolveFacilityUnitErrorsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/tag",
          label: "Tag",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatefacilityrequest",
          label: "UpdateFacilityRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/type",
          label: "Type",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/addclusterunitsrequest",
          label: "AddClusterUnitsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createclusterrequest",
          label: "CreateClusterRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createnoderequest",
          label: "CreateNodeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/essential",
          label: "Essential",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/unit",
          label: "Unit",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/gpurelation",
          label: "GPURelation",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/gpu",
          label: "GPU",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/machine",
          label: "Machine",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pod",
          label: "Pod",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/device",
          label: "Device",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listessentialsrequest",
          label: "ListEssentialsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listessentialsresponse",
          label: "ListEssentialsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listgpurelationsbymachinerequest",
          label: "ListGPURelationsByMachineRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listgpurelationsbymachineresponse",
          label: "ListGPURelationsByMachineResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listgpurelationsbymodelrequest",
          label: "ListGPURelationsByModelRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listgpurelationsbymodelresponse",
          label: "ListGPURelationsByModelResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listkubernetesnodelabelsrequest",
          label: "ListKubernetesNodeLabelsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listkubernetesnodelabelsresponse",
          label: "ListKubernetesNodeLabelsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/labelsentry",
          label: "LabelsEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listpluginsrequest",
          label: "ListPluginsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listpluginsresponse",
          label: "ListPluginsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/plugin",
          label: "Plugin",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/chart",
          label: "Chart",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatekubernetesnodelabelsrequest",
          label: "UpdateKubernetesNodeLabelsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/labelsentry",
          label: "LabelsEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatekubernetesnodelabelsresponse",
          label: "UpdateKubernetesNodeLabelsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/labelsentry",
          label: "LabelsEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createiprangerequest",
          label: "CreateIPRangeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createnetworkrequest",
          label: "CreateNetworkRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deleteiprangerequest",
          label: "DeleteIPRangeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletenetworkrequest",
          label: "DeleteNetworkRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listnetworksrequest",
          label: "ListNetworksRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listnetworksresponse",
          label: "ListNetworksResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/network",
          label: "Network",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fabric",
          label: "Fabric",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/ipaddress",
          label: "IPAddress",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/iprange",
          label: "IPRange",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/statistics",
          label: "Statistics",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/subnet",
          label: "Subnet",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/vlan",
          label: "VLAN",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatefabricrequest",
          label: "UpdateFabricRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updateiprangerequest",
          label: "UpdateIPRangeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatesubnetrequest",
          label: "UpdateSubnetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatevlanrequest",
          label: "UpdateVLANRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/addmachinetagsrequest",
          label: "AddMachineTagsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createmachinerequest",
          label: "CreateMachineRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createtagrequest",
          label: "CreateTagRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletemachinerequest",
          label: "DeleteMachineRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletetagrequest",
          label: "DeleteTagRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getmachinerequest",
          label: "GetMachineRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/gettagrequest",
          label: "GetTagRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listmachinesrequest",
          label: "ListMachinesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listmachinesresponse",
          label: "ListMachinesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listtagsrequest",
          label: "ListTagsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listtagsresponse",
          label: "ListTagsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/machine",
          label: "Machine",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/blockdevice",
          label: "BlockDevice",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/hardwareinformationentry",
          label: "HardwareInformationEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/numanode",
          label: "NUMANode",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/networkinterface",
          label: "NetworkInterface",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/nodedevice",
          label: "NodeDevice",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/workloadannotationsentry",
          label: "WorkloadAnnotationsEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/poweroffmachinerequest",
          label: "PowerOffMachineRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/removemachinetagsrequest",
          label: "RemoveMachineTagsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/tag",
          label: "Tag",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/result",
          label: "Result",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/level",
          label: "Level",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/checkhealthrequest",
          label: "CheckHealthRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/checkhealthresponse",
          label: "CheckHealthResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getpremiumtierrequest",
          label: "GetPremiumTierRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getprometheusrequest",
          label: "GetPrometheusRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/premiumtier",
          label: "PremiumTier",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/prometheus",
          label: "Prometheus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updateconfigrequest",
          label: "UpdateConfigRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/accessmode",
          label: "AccessMode",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/type",
          label: "Type",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/status",
          label: "Status",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/operation",
          label: "Operation",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/cephblockdevice",
          label: "CephBlockDevice",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/configuration",
          label: "Configuration",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/bootimage",
          label: "BootImage",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/architecturestatusmapentry",
          label: "ArchitectureStatusMapEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/bootimageselection",
          label: "BootImageSelection",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/helmrepository",
          label: "HelmRepository",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/ntpserver",
          label: "NTPServer",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/packagerepository",
          label: "PackageRepository",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createbootimagerequest",
          label: "CreateBootImageRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createtestresultrequest",
          label: "CreateTestResultRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletetestresultrequest",
          label: "DeleteTestResultRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/externalobjectservice",
          label: "ExternalObjectService",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fio",
          label: "FIO",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/input",
          label: "Input",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/output",
          label: "Output",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/throughput",
          label: "Throughput",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/latency",
          label: "Latency",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getconfigurationrequest",
          label: "GetConfigurationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/importbootimagesrequest",
          label: "ImportBootImagesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/internalobjectservice",
          label: "InternalObjectService",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/isimportingbootimagesrequest",
          label: "IsImportingBootImagesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/isimportingbootimagesresponse",
          label: "IsImportingBootImagesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listbootimageselectionsrequest",
          label: "ListBootImageSelectionsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listbootimageselectionsresponse",
          label: "ListBootImageSelectionsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listinternalobjectservicesrequest",
          label: "ListInternalObjectServicesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listinternalobjectservicesresponse",
          label: "ListInternalObjectServicesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listtestresultsrequest",
          label: "ListTestResultsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listtestresultsresponse",
          label: "ListTestResultsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/networkfilesystem",
          label: "NetworkFileSystem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/setdefaultbootimagerequest",
          label: "SetDefaultBootImageRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/testresult",
          label: "TestResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatehelmrepositoryrequest",
          label: "UpdateHelmRepositoryRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatentpserverrequest",
          label: "UpdateNTPServerRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatepackagerepositoryrequest",
          label: "UpdatePackageRepositoryRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/warp",
          label: "Warp",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/input",
          label: "Input",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/output",
          label: "Output",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/throughput",
          label: "Throughput",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/metrics",
          label: "Metrics",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createmodelrequest",
          label: "CreateModelRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deletemodelrequest",
          label: "DeleteModelRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getmodelrequest",
          label: "GetModelRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listmodelsrequest",
          label: "ListModelsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listmodelsresponse",
          label: "ListModelsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/model",
          label: "Model",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatestatusrequest",
          label: "UpdateStatusRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/watchstatusrequest",
          label: "WatchStatusRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/watchstatusresponse",
          label: "WatchStatusResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createscoperequest",
          label: "CreateScopeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listscopesrequest",
          label: "ListScopesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listscopesresponse",
          label: "ListScopesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/scope",
          label: "Scope",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
